export const LIGHTING_PRESETS = [
  {
    id: 'bright-warm',
    label: 'Helder warm',
    description: 'Meer licht en een warme sfeer.',
    background: '#f7efe2',
    fog: '#efe2d0',
    hemiSkyColor: '#fff4dd',
    hemiGroundColor: '#d9c3a1',
    hemiIntensity: 0.96,
    sunColor: '#ffd9a3',
    sunIntensity: 1.18,
    sunPosition: [20, 38, 14],
    exposure: 1.08
  },
  {
    id: 'bright-neutral',
    label: 'Helder neutraal',
    description: 'Meer licht met een rustige balans.',
    background: '#f2f3ee',
    fog: '#e5e7e0',
    hemiSkyColor: '#fbfcf7',
    hemiGroundColor: '#c9cec3',
    hemiIntensity: 0.97,
    sunColor: '#edf0e8',
    sunIntensity: 1.16,
    sunPosition: [20, 38, 14],
    exposure: 1.06
  },
  {
    id: 'bright-cold',
    label: 'Helder koel',
    description: 'Meer licht en een frisse toon.',
    background: '#eef3f8',
    fog: '#dde7f2',
    hemiSkyColor: '#f2f8ff',
    hemiGroundColor: '#b5c8d8',
    hemiIntensity: 0.98,
    sunColor: '#d9ecff',
    sunIntensity: 1.14,
    sunPosition: [20, 38, 14],
    exposure: 1.04
  },
  {
    id: 'balanced-warm',
    label: 'Zacht warm',
    description: 'Een evenwichtige warme sfeer.',
    background: '#f4eadf',
    fog: '#eadccf',
    hemiSkyColor: '#fff0df',
    hemiGroundColor: '#d5bea3',
    hemiIntensity: 0.84,
    sunColor: '#f7cf97',
    sunIntensity: 0.96,
    sunPosition: [19, 34, 13],
    exposure: 0.96
  },
  {
    id: 'balanced-neutral',
    label: 'Zacht neutraal',
    description: 'Evenwichtige belichting zonder kleurzweem.',
    background: '#edf0eb',
    fog: '#dde2db',
    hemiSkyColor: '#f7f9f4',
    hemiGroundColor: '#bfc7bb',
    hemiIntensity: 0.85,
    sunColor: '#e7ebe4',
    sunIntensity: 0.95,
    sunPosition: [19, 34, 13],
    exposure: 0.95
  },
  {
    id: 'balanced-cold',
    label: 'Zacht koel',
    description: 'Een evenwichtige koele sfeer.',
    background: '#edf1f6',
    fog: '#dde5ee',
    hemiSkyColor: '#f4f8ff',
    hemiGroundColor: '#bac9d8',
    hemiIntensity: 0.86,
    sunColor: '#d0e4f6',
    sunIntensity: 0.94,
    sunPosition: [19, 34, 13],
    exposure: 0.94
  },
  {
    id: 'dim-warm',
    label: 'Gedimd warm',
    description: 'Zachter licht met een warme gloed.',
    background: '#efe4d6',
    fog: '#e1d1bf',
    hemiSkyColor: '#f5e8d5',
    hemiGroundColor: '#c9af92',
    hemiIntensity: 0.62,
    sunColor: '#f2c58d',
    sunIntensity: 0.7,
    sunPosition: [18, 28, 12],
    exposure: 0.84
  },
  {
    id: 'dim-neutral',
    label: 'Gedimd neutraal',
    description: 'Minder licht met een neutrale balans.',
    background: '#e6e8e3',
    fog: '#d8ddd7',
    hemiSkyColor: '#f1f3ee',
    hemiGroundColor: '#aeb6ab',
    hemiIntensity: 0.63,
    sunColor: '#dde1db',
    sunIntensity: 0.69,
    sunPosition: [18, 28, 12],
    exposure: 0.82
  },
  {
    id: 'dim-cold',
    label: 'Gedimd koel',
    description: 'Zachter licht met een koelere uitstraling.',
    background: '#e8edf4',
    fog: '#d5e0ec',
    hemiSkyColor: '#edf5ff',
    hemiGroundColor: '#aebfd0',
    hemiIntensity: 0.64,
    sunColor: '#bfd8ef',
    sunIntensity: 0.68,
    sunPosition: [18, 28, 12],
    exposure: 0.8
  },
  {
    id: 'dark-warm',
    label: 'Donker warm',
    description: 'Een diepere warme sfeer met weinig licht.',
    background: '#e5d7c8',
    fog: '#d4c3b2',
    hemiSkyColor: '#efddca',
    hemiGroundColor: '#b79477',
    hemiIntensity: 0.45,
    sunColor: '#e8b97c',
    sunIntensity: 0.48,
    sunPosition: [16, 24, 10],
    exposure: 0.7
  },
  {
    id: 'dark-neutral',
    label: 'Donker neutraal',
    description: 'Weinig licht met een rustige balans.',
    background: '#dfe2dd',
    fog: '#cfd5cf',
    hemiSkyColor: '#e9ece7',
    hemiGroundColor: '#9ea79c',
    hemiIntensity: 0.46,
    sunColor: '#d2d7d0',
    sunIntensity: 0.46,
    sunPosition: [16, 24, 10],
    exposure: 0.68
  },
  {
    id: 'dark-cold',
    label: 'Donker koel',
    description: 'Een diepere koele sfeer met weinig licht.',
    background: '#d8e0ea',
    fog: '#c8d4e0',
    hemiSkyColor: '#e3ebf5',
    hemiGroundColor: '#8fa2b8',
    hemiIntensity: 0.44,
    sunColor: '#b8d2ea',
    sunIntensity: 0.45,
    sunPosition: [16, 24, 10],
    exposure: 0.66
  }
]

export const DEFAULT_LIGHTING_PRESET_ID = 'bright-warm'

export function getLightingPresetById(presetId) {
  return LIGHTING_PRESETS.find((preset) => preset.id === presetId) ?? LIGHTING_PRESETS[0]
}
