-- Dedicated reusable scene templates for dashboard/editor start flows.
-- Run this after 006_app_scenes_workspace_and_rls.sql.

create table if not exists public.app_scene_templates (
  id integer generated by default as identity primary key,
  template_key text not null unique,
  name text not null,
  description text null,
  schema_version integer not null default 1,
  scene_data jsonb not null,
  thumbnail_url text null,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_by uuid null references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists app_scene_templates_active_sort_idx
  on public.app_scene_templates (is_active, sort_order, id);

create or replace function public.set_app_scene_templates_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_app_scene_templates_updated_at on public.app_scene_templates;
create trigger trg_app_scene_templates_updated_at
before update on public.app_scene_templates
for each row
execute function public.set_app_scene_templates_updated_at();

alter table public.app_scene_templates enable row level security;

drop policy if exists app_scene_templates_select_authenticated on public.app_scene_templates;
drop policy if exists app_scene_templates_insert_consultant on public.app_scene_templates;
drop policy if exists app_scene_templates_update_consultant on public.app_scene_templates;
drop policy if exists app_scene_templates_delete_consultant on public.app_scene_templates;

create policy app_scene_templates_select_authenticated
on public.app_scene_templates
for select
to authenticated
using (is_active = true or public.is_consultant(auth.uid()));

create policy app_scene_templates_insert_consultant
on public.app_scene_templates
for insert
to authenticated
with check (public.is_consultant(auth.uid()));

create policy app_scene_templates_update_consultant
on public.app_scene_templates
for update
to authenticated
using (public.is_consultant(auth.uid()))
with check (public.is_consultant(auth.uid()));

create policy app_scene_templates_delete_consultant
on public.app_scene_templates
for delete
to authenticated
using (public.is_consultant(auth.uid()));

insert into public.app_scene_templates (
  id,
  template_key,
  name,
  description,
  schema_version,
  scene_data,
  sort_order,
  is_active
)
values
(
  0,
  'empty-v1',
  'Template - Empty',
  'Lege startopzet met alleen een basisvloer.',
  1,
  $$
  {
    "id": "template-empty-v1",
    "name": "Template - Empty",
    "schemaVersion": 1,
    "createdAt": "2026-06-03T00:00:00.000Z",
    "updatedAt": "2026-06-03T00:00:00.000Z",
    "editorSettings": {
      "grid": {
        "cellSize": 1,
        "groundSize": 24,
        "origin": [0, 0, 0]
      },
      "lighting": {
        "presetId": "bright-warm"
      },
      "template": {
        "key": "empty-v1",
        "title": "Empty",
        "description": "Lege basisruimte."
      }
    },
    "objects": [
      {
        "id": "floor-main",
        "kind": "floor",
        "assetRef": "floor-base",
        "transform": {
          "position": [0, -0.07, 0],
          "rotation": [0, 0, 0],
          "scale": [20, 1, 20]
        },
        "appearance": {
          "color": "#7a8fa0",
          "texture": null,
          "materialOverrides": null,
          "finish": {
            "roughness": 0.56,
            "metalness": 0.03
          }
        },
        "metadata": null,
        "interaction": null
      }
    ]
  }
  $$::jsonb,
  0,
  true
),
(
  1,
  'serenity-garden-v1',
  'Template - Serenity Garden',
  'Rustige basisopzet met een centraal herdenkingsvlak.',
  1,
  $$
  {
    "id": "template-serenity-garden-v1",
    "name": "Template - Serenity Garden",
    "schemaVersion": 1,
    "createdAt": "2026-06-03T00:00:00.000Z",
    "updatedAt": "2026-06-03T00:00:00.000Z",
    "editorSettings": {
      "grid": {
        "cellSize": 1,
        "groundSize": 24,
        "origin": [0, 0, 0]
      },
      "lighting": {
        "presetId": "bright-warm"
      },
      "template": {
        "key": "serenity-garden-v1",
        "title": "Serenity Garden",
        "description": "Rustige basisopzet met een centraal herdenkingsvlak."
      }
    },
    "objects": [
      {
        "id": "floor-main",
        "kind": "floor",
        "assetRef": "floor-base",
        "transform": {
          "position": [0, -0.07, 0],
          "rotation": [0, 0, 0],
          "scale": [20, 1, 20]
        },
        "appearance": {
          "color": "#7a8fa0",
          "texture": {
            "textureId": "grass-001",
            "uvScale": [2, 2],
            "rotation": 0,
            "intensity": 1
          },
          "materialOverrides": null,
          "finish": {
            "roughness": 0.62,
            "metalness": 0.02
          }
        },
        "metadata": null,
        "interaction": null
      },
      {
        "id": "marker-left",
        "kind": "shape",
        "assetRef": "cylinder",
        "transform": {
          "position": [-3.2, 0.8, -2.4],
          "rotation": [0, 0.35, 0],
          "scale": [1.1, 1.6, 1.1]
        },
        "appearance": {
          "color": "#d9be99",
          "texture": null,
          "materialOverrides": null,
          "finish": {
            "roughness": 0.6,
            "metalness": 0.05
          }
        },
        "metadata": null,
        "interaction": null
      },
      {
        "id": "marker-right",
        "kind": "shape",
        "assetRef": "cylinder",
        "transform": {
          "position": [3.4, 0.8, -2.1],
          "rotation": [0, -0.4, 0],
          "scale": [1.1, 1.6, 1.1]
        },
        "appearance": {
          "color": "#cbb7a4",
          "texture": null,
          "materialOverrides": null,
          "finish": {
            "roughness": 0.56,
            "metalness": 0.06
          }
        },
        "metadata": null,
        "interaction": null
      },
      {
        "id": "marker-back",
        "kind": "shape",
        "assetRef": "cone",
        "transform": {
          "position": [0.2, 1.1, -4.4],
          "rotation": [0, 0, 0],
          "scale": [1.2, 2, 1.2]
        },
        "appearance": {
          "color": "#9fa68f",
          "texture": null,
          "materialOverrides": null,
          "finish": {
            "roughness": 0.58,
            "metalness": 0.07
          }
        },
        "metadata": null,
        "interaction": null
      },
      {
        "id": "altar-shape",
        "kind": "shape",
        "assetRef": "square",
        "transform": {
          "position": [0, 0.5, 1.6],
          "rotation": [0, 0, 0],
          "scale": [2.8, 1, 1.4]
        },
        "appearance": {
          "color": "#d8c9b8",
          "texture": null,
          "materialOverrides": null,
          "finish": {
            "roughness": 0.52,
            "metalness": 0.03
          }
        },
        "metadata": null,
        "interaction": null
      }
    ]
  }
  $$::jsonb,
  10,
  true
)
on conflict (id)
do update set
  template_key = excluded.template_key,
  name = excluded.name,
  description = excluded.description,
  schema_version = excluded.schema_version,
  scene_data = excluded.scene_data,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.app_scene_templates', 'id'),
  greatest((select coalesce(max(id), 0) from public.app_scene_templates), 1),
  true
);